#!/usr/bin/env python3
"""Generates src/schema.rs from pi's settings reference (docs/settings.md).

Run after pi's settings change:
    python3 crates/pi_settings/gen_schema.py [path/to/pi/packages/coding-agent/docs/settings.md]
The default path is the sibling pi checkout. Each table row becomes one `Setting`;
`##` and `###` headings become categories.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DOC = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "../../../pi/packages/coding-agent/docs/settings.md"
OUT = HERE / "src/schema.rs"
PIPE = "\u0000"

# Headings as the design names them; the rest keep the docs' wording.
CATEGORY = {
    "Model and thinking": "Model & thinking",
    "Sessions and context": "Sessions & context",
    "Terminal and display": "Terminal & display",
    "Network and retries": "Network & retries",
    "Updates, telemetry, and warnings": "Updates & telemetry",
}
# Words that read better in capitals.
UPPER = {"http", "npm", "id", "json", "url", "ms"}


def title(key):
    words = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", key.rsplit(".", 1)[-1]).lower().split()
    words = [w.upper() if w in UPPER else w for w in words]
    return " ".join(words)[:1].upper() + " ".join(words)[1:]


def code_spans(text):
    return re.findall(r"`([^`]*)`", text)


def kind(type_text):
    t = type_text.strip()
    if t == "boolean":
        return "Kind::Bool"
    if t == "number":
        return "Kind::Number"
    if t == "string":
        return "Kind::Text"
    if t.replace("`", "") == "string[]":
        return "Kind::List"
    if t in ("object", "array"):
        return "Kind::Json"
    # A union of literals: `"a" | "b"`, `0 | 1`, `boolean | "auto"`, `... | false`.
    options = []
    for part in t.replace("`", "").split(PIPE):
        part = part.strip()
        if part == "boolean":
            options += ["true", "false"]
        else:
            json.loads(part)
            options.append(part)
    return "Kind::Choice(&[" + ", ".join(json.dumps(o) for o in options) + "])"


def default(kind_text, text):
    """A JSON literal for a concrete default, else None; the text is kept for display."""
    spans = code_spans(text)
    if not spans or text.replace("`", "").strip() != ", ".join(spans):
        return None
    if kind_text == "Kind::List":
        values = []
        for span in spans:
            try:
                value = json.loads(span)
            except ValueError:
                value = span
            values.extend(value if isinstance(value, list) else [value])
        return json.dumps(values)
    if len(spans) != 1:
        return None
    try:
        return json.dumps(json.loads(spans[0]))
    except ValueError:
        return json.dumps(spans[0])


def plain(text):
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    return re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)


def main():
    rows = []
    category = None
    for line in DOC.read_text().splitlines():
        heading = re.match(r"^(##|###) (.+)$", line)
        if heading:
            category = CATEGORY.get(heading.group(2), heading.group(2))
            continue
        if not line.startswith("| `"):
            continue
        cells = [c.strip().replace(PIPE, "|") for c in line.replace("\\|", PIPE).strip("|").split("|")]
        key = code_spans(cells[0])[0]
        type_text = cells[1].replace("|", PIPE)
        k = kind(type_text)
        description = plain(cells[3])
        user_only = "Can only be set in agent-directory settings" in description or "Global setting only" in description
        rows.append((key, category, title(key), k, default(k, cells[2]), plain(cells[2]), description, user_only))

    out = [
        "// Generated by gen_schema.py from pi's docs/settings.md. Do not edit; run the script.",
        "use crate::{Kind, Scope, Setting};",
        "",
        "pub const SETTINGS: &[Setting] = &[",
    ]
    for key, cat, name, k, value, text, description, user_only in rows:
        out.append("    Setting {")
        out.append(f"        key: {json.dumps(key)},")
        out.append(f"        category: {json.dumps(cat)},")
        out.append(f"        title: {json.dumps(name)},")
        out.append(f"        kind: {k},")
        out.append(f"        default: {'Some(' + json.dumps(value) + ')' if value is not None else 'None'},")
        out.append(f"        default_text: {json.dumps(text)},")
        out.append(f"        description: {json.dumps(description, ensure_ascii=False)},")
        out.append(f"        scope: Scope::{'UserOnly' if user_only else 'Any'},")
        out.append("    },")
    out.append("];")
    OUT.write_text("\n".join(out) + "\n")
    print(f"{len(rows)} settings -> {OUT.relative_to(HERE)}")


if __name__ == "__main__":
    main()
