//! pi-desktop's own settings (design study 06). Written by hand: pi documents
//! none of them. `Scope::Any` marks the few a project's `.pi/pi-desktop.json` may
//! override; the rest live only in the app's own file.
use pi_settings::{Kind, Scope, Setting};

pub const DESKTOP: &[Setting] = &[
    Setting {
        key: "general.reopenSessions",
        category: "General",
        title: "Reopen sessions at launch",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "Opens the sessions that were open when the app last quit.",
        scope: Scope::UserOnly,
    },
    Setting {
        key: "general.confirmClose",
        category: "General",
        title: "Ask before closing a running session",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "Asks before closing a session that is running or has queued messages, a draft or unsaved files.",
        scope: Scope::UserOnly,
    },
    Setting {
        key: "general.rememberDismissed",
        category: "General",
        title: "Remember \u{201c}Not now\u{201d} answers",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "Keeps answers such as \u{201c}Not now\u{201d} to turning on jj in a git project across launches. Off asks again after each launch.",
        scope: Scope::UserOnly,
    },
    Setting {
        key: "appearance.theme",
        category: "Appearance",
        title: "Theme",
        kind: Kind::Choice(&["\"system\"", "\"evening\"", "\"moonstone\""]),
        default: Some("\"system\""),
        default_text: "system",
        description: "Evening is dark and Moonstone light; System follows the operating system. Ctrl+Shift+T switches until the next launch.",
        scope: Scope::UserOnly,
    },
    Setting {
        key: "jj.offer",
        category: "jj",
        title: "Offer jj in git projects",
        kind: Kind::Choice(&["\"ask\"", "\"never\""]),
        default: Some("\"ask\""),
        default_text: "ask",
        description: "Whether a git project without jj shows the offer to turn jj on.",
        scope: Scope::Any,
    },
    Setting {
        key: "jj.snapshotBeforeCommands",
        category: "jj",
        title: "Snapshot before each command",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "Takes a jj snapshot before each bash call, so the files a command changes can be restored to just before it.",
        scope: Scope::Any,
    },
    Setting {
        key: "jj.tools",
        category: "jj",
        title: "Let pi read jj history",
        kind: Kind::Bool,
        default: Some("false"),
        default_text: "false",
        description: "Gives pi read-only jj_log, jj_diff and jj_show tools, answered by the app. New sessions get them.",
        scope: Scope::Any,
    },
    Setting {
        key: "jj.turnBars",
        category: "jj",
        title: "Turn bars in the editor",
        kind: Kind::Choice(&["\"alt\"", "\"never\""]),
        default: Some("\"alt\""),
        default_text: "alt",
        description: "While the key is held, marks each line in a file tab with the turn that last changed it; click a line for that turn.",
        scope: Scope::Any,
    },
    Setting {
        key: "jj.parallelSessions",
        category: "jj",
        title: "Sessions working in the same folder",
        kind: Kind::Choice(&["\"ask\"", "\"workspace\"", "\"same\""]),
        default: Some("\"ask\""),
        default_text: "ask",
        description: "When a session starts work in a folder another session is working in: ask, give it its own jj workspace, or share the folder.",
        scope: Scope::Any,
    },
    Setting {
        key: "languageServers.afterEdits",
        category: "Language servers",
        title: "Tell pi about errors after edits",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "After pi's edit and write calls, tells pi about new language-server errors in that file. Needs language services on for the project (Files).",
        scope: Scope::Any,
    },
    Setting {
        key: "languageServers.beforeRunEnds",
        category: "Language servers",
        title: "Check files before a run ends",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "When a run ends, tells pi about errors in the other files that changed during it.",
        scope: Scope::Any,
    },
    Setting {
        key: "editor.fontSize",
        category: "Editor",
        title: "Font size",
        kind: Kind::Number,
        default: Some("11.5"),
        default_text: "11.5",
        description: "The font size in file tabs, in pixels, from 8 to 32.",
        scope: Scope::UserOnly,
    },
    Setting {
        key: "editor.problemCard",
        category: "Editor",
        title: "Show the problem card on hover",
        kind: Kind::Bool,
        default: Some("true"),
        default_text: "true",
        description: "One card for a problem, the hover text, a quick fix and Ask pi to fix. Off shows Zed's own hover popovers instead.",
        scope: Scope::UserOnly,
    },
    Setting {
        key: "terminal.shell",
        category: "Terminal",
        title: "Shell",
        kind: Kind::Text,
        default: None,
        default_text: "Automatic",
        description: "The program new terminals run. Automatic uses your login shell.",
        scope: Scope::UserOnly,
    },
];
